In [2]:
import numpy as np

In [3]:
z = np.array([[1, 2], [3, 4]])

In [4]:
z

array([[1, 2],
       [3, 4]])

In [5]:
z[1, 1]

4

In [6]:
z[1,0]

3

In [7]:
z[1, :]

array([3, 4])

In [8]:
z[:, 0]

array([1, 3])

In [9]:
z = np.linspace(2, 4, 5)

In [10]:
z

array([ 2. ,  2.5,  3. ,  3.5,  4. ])

In [11]:
indices = np.array((0, 2, 3))

In [12]:
indices

array([0, 2, 3])

In [13]:
z[indices]

array([ 2. ,  3. ,  3.5])

In [14]:
A = np.array((4, 3, 2, 1))

In [15]:
A

array([4, 3, 2, 1])

In [16]:
A.sort()

In [17]:
A

array([1, 2, 3, 4])

In [18]:
A.shape = [2, 2]

In [19]:
A

array([[1, 2],
       [3, 4]])

In [20]:
A.T

array([[1, 3],
       [2, 4]])

In [26]:
A = np.array((1, 2))

In [24]:
B = np.array((10, 20))

In [27]:
A

array([1, 2])

In [28]:
B

array([10, 20])

In [29]:
A @ B

50

In [30]:
a = np.random.randn(3)

In [31]:
a

array([-0.79768117,  0.55789377,  1.64050997])

In [33]:
b = np.empty_like(a)

In [34]:
np.copyto(b, a)

In [35]:
b

array([-0.79768117,  0.55789377,  1.64050997])

In [36]:
b[:] = 0

In [37]:
b

array([ 0.,  0.,  0.])

In [38]:
a

array([-0.79768117,  0.55789377,  1.64050997])

In [39]:
z = np.array([1, 2, 3])

In [40]:
np.sin(z)

array([ 0.84147098,  0.90929743,  0.14112001])

In [43]:
z

array([1, 2, 3])

In [44]:
x = np.random.randn(4)

In [45]:
x

array([ 0.49583405,  0.24823448,  0.72387171, -0.89195427])

In [46]:
np.where(x > 0, 1, 0)

array([1, 1, 1, 0])

In [47]:
def f(x): return 1 if x > 0 else 0

In [48]:
f = np.vectorize(f)

In [49]:
f(x)

array([1, 1, 1, 0])

In [50]:
z = np.array([2, 3])

In [51]:
y = np.array([2, 3])

In [52]:
z == y

array([ True,  True], dtype=bool)

In [53]:
y[0] = 5

In [54]:
z == y

array([False,  True], dtype=bool)

# exercise1

In [60]:
%matplotlib inline

In [61]:
import numpy as np
import matplotlib.pyplot as plt

In [62]:
?len

In [65]:
def p(x, coeff):
    X = np.empty(len(coeff))
    X[0] = 1
    X[1:] = x
    y = np.cumprod(X)
    return coeff @ y

In [66]:
coef = np.ones(3)
print(coef)
print(p(1, coef))
q = np.poly1d(coef)
print(q(1))

[ 1.  1.  1.]
3.0
3.0


In [67]:
?np.poly1d

# exercise2

In [70]:
from random import uniform

def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]

In [86]:
uniform(0, 1)

0.05576552237094823

In [78]:
?uniform

In [87]:
q = [0.25, 0.15, 0.6]
print(sample(q))

1


In [1]:
import numpy as np
from numpy import cumsum
from numpy.random import uniform

def sample2(q):
    U = uniform(0,1)
    z = np.asarray(q)
    Q = z.cumsum()
    return Q.searchsorted(U)

In [20]:
q = [0.1, 0.2, 0.3, 0.4]
Z = np.asarray([sample2(q) for i in range(100000)])
print(np.average(Z))

2.00108


In [4]:
import numpy as np
from numpy import cumsum
from numpy.random import uniform

class discreteRV:
    
    def __init__(self, q):
        self.q = np.asarray(q)
        self.Q = cumsum(q)
        
    def draw(self, k=1):
        return self.Q.searchsorted(uniform(0, 1, size = k))

In [3]:
print(discreteRV.__dict__)

{'__module__': '__main__', '__doc__': None, 'draw': <function discreteRV.draw at 0x000002B0880609D8>, '__init__': <function discreteRV.__init__ at 0x000002B087C7B730>, '__weakref__': <attribute '__weakref__' of 'discreteRV' objects>, '__dict__': <attribute '__dict__' of 'discreteRV' objects>}


In [5]:
q = [0.25, 0.75]
d1 = discreteRV(q)

In [6]:
print(d1.draw(3))

[0 1 0]


Object `average` not found.


# exercise3

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

class ECDF(object):
    
    def __init__(self, observations):
        self.observations = np.asarray(observations)
        
    def __call__(self, x):
        return np.mean(self.observations <= x)
    
    def 